### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lucaingold** [homespun/homebridge-platform-yoctopuce#1]
Will this also work with a simple yoctopuce relay? Thank you in advance!

**Comment by mrose17** [comment]
at present, the plugin does monitoring only. it could be made to work with a relay. after all, it's just an on/off switch. are you interested in doing the work?

**Comment by ff12** [comment]
i've tried to install the homebridge-plugin for my yocto-voc on raspbian Jessie but i get several errors (Permission denied) i've reported! Did i miss something?


`pi@raspberrypi:~ $ sudo npm install -g homebridge-platform-yoctopuce
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://githu                                                                                                             b.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-                                                                                                             a3d009fd
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp                                                                                                             /git-clone-a3d009fd': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-01T01_22_29_607Z-debug.log

pi@raspberrypi:~ $ sudo npm install -g homebridge-accessory-neurio
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://githu                                                                                                             b.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-                                                                                                             e546be6a
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp                                                                                                             /git-clone-e546be6a': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-01T01_22_51_592Z-debug.log
`

**Comment by mrose17** [comment]
my guess is that `sudo` and `npm` do not work well together. 

what *exact* command did you use to install homebridge?

**Comment by ff12** [comment]
thanks for your answer.

I had used :  `sudo npm install -g --unsafe-perm homebridge`

i've tried :
```
sudo apt-get install libpcap-dev
sudo npm install -g --unsafe-perm homebridge-accessory-neurio
sudo npm install -g --unsafe-perm homebridge-platform-yoctopuce
```
 and it has worked!

When i run homebridge i get

[11/4/2017, 1:16:11 AM] [homebridge-platform-yoctopuce.Yoctopuce] didFinishLaunching
[ listening on wlan0: http://192.168.1.11:40817 ]
[ listening on lo0: http://127.0.0.1:46037 ]

but the Yocto-voc doesn't appear in homekit not being supported.

**Comment by mrose17** [comment]
@ff12 - thanks for the feedback. 

i pushed a new version of this package. it may work with voc (i can't test here). let me know what you see. thanks!

**Comment by ff12** [comment]
I've never used dynamic platforms, but nothing seems to happen.
I'm not sure but In the the config.json I've added:
```
 "Platforms":
  [
        {"platform": "Yoctopuce",
        "name": "Yoctopuce"}
  ]
```
Although it wasn't written in the README.md file. If i didn't, the platform didn't load.
This is what i get: 

[11/11/2017, 1:27:12 AM] Loaded plugin: homebridge-platform-yoctopuce
[11/11/2017, 1:27:12 AM] Registering platform 'homebridge-platform-yoctopuce.Yoctopuce'
[11/11/2017, 1:27:12 AM] Loaded config.json with 0 accessories and 1 platforms.
[11/11/2017, 1:27:12 AM] Loading 1 platforms...
[11/11/2017, 1:27:12 AM] [Yoctopuce] Initializing Yoctopuce platform...
[11/11/2017, 1:27:12 AM] Loading 0 accessories...
[11/11/2017, 1:27:13 AM] [Yoctopuce] didFinishLaunching

**Comment by mrose17** [comment]
sorry for missing your reply.

oops! the README is incomplete. i have fixed it.

so, what yoctopuce devices are you using?  

Thanks!
